### ISSUE TITLE
Issues with scrolling and images when fullscreen

### ISSUE THREAD

**Issue by LukeRP** [andrewbanchich/highlights-jekyll-theme#3]
Hey man. I haven't really fiddled with anything but the background pictures and the info sections, but the kind of "soft-scroll" behavior from clicking the "next" arrow doesn't work anymore (it goes straight down to the next section), and the images don't appear in the background. I made sure they were all exactly 1600x1000. 

Any thoughts? 
site: https://lukerp.github.io/CV/
code: https://github.com/LukeRP/CV/

I'm still new to github, so I don't know how to compare forks directly or anything. 

Thanks a lot.

**Comment by andrewbanchich** [comment]
Hi @LukeRP ,

I took a look at your site and the console showed this when it loaded:

```
Loading failed for the <script> with source “https://github.com/LukeRP/CV/assets/js/jquery.min.js”.
CV:138
Loading failed for the <script> with source “https://github.com/LukeRP/CV/assets/js/jquery.scrollex.min.js”.
CV:139
Loading failed for the <script> with source “https://github.com/LukeRP/CV/assets/js/jquery.scrolly.min.js”.
CV:140
Loading failed for the <script> with source “https://github.com/LukeRP/CV/assets/js/skel.min.js”.
CV:141
Loading failed for the <script> with source “https://github.com/LukeRP/CV/assets/js/util.js”.
CV:142
Loading failed for the <script> with source “https://github.com/LukeRP/CV/assets/js/main.js”.
CV:144
```

That JavaScript is what powers the smooth scrolling, so since it can't find it it's just jumping instantly to the next spot on the page. I think you just need to edit your `_config.yml` file with the right path.

Let me know if that doesn't work for you.

**Comment by LukeRP** [comment]
Yeah, that did it. In the `_config.yml` file there's "base_url" which needs to have the "/highlights-jekyll-theme", but then URL, confusingly, needs to stay blank. I had put "lukerp.github.io".  
  
Thanks again for your help, beautiful thing you've brought to github pages.

**Comment by andrewbanchich** [comment]
Thanks!
